### ISSUE TITLE
[Feature Request] - Auto level toggle

### ISSUE THREAD

**Issue by yamamushi** [Dimencia/DU-Orbital-Hud#10]
It would be extremely handy to have an auto-level hotkey with this, something that will ... well, automatically levels your ship to the ground. There are other nav scripts (BetterNav, for example) that have this feature on the "g" key to auto-level your construct, and it's become quite an indispensable feature to have for many heavy ships to leave the atmosphere on any given planet easier. 

If there's already a hotkey for that, I apologize because I didn't see it in the documentation.

**Comment by Dimencia** [comment]
There isn't, and it's not a bad idea, but we're kind of short on hotkeys.  I could maybe fit it on either Z or alt+7, neither of which is all that great... Z maybe.  
But, why not just use AutoRoll? Legitimate question, does AutoRoll not work on moons or etc?

**Comment by yamamushi** [comment]
Z would be great :D 

I just know that it's a bit more aggressive than autoroll, and it's become rather second nature to use for everything from taking off with heavy cargo to just pulling into a hanger evenly. 

Thanks!!

**Comment by Dimencia** [comment]
So btw, turns out I was looking at an AZERTY keyboard layout, we're legitimately out of keys, I already have plans for the rest.
This auto-level is still on my 'eventually' todo list but for now it can't come until after a rework of the controls to fit more things into it (contextual)

**Comment by MJLaukala** [comment]
I really wish they would just let use any keys for the scripts.
What I would really like to see is the use of a screen. I would much rather have all this on a screen rather than attached to my hud and if that were the case, you could have a series of navigation interface button on the screen rather than being tied to the player hud and limited hotkeys. I plan on forking the repo and implementing this myself for a programming board... if I ever find the time.

**Comment by yamamushi** [comment]
Indeed, if you drew some of this to a screen, then we could have a huge variety of options here.

**Comment by Archaegeo** [comment]
We try not to require any elements but support all.
