### ISSUE TITLE
Autopilot does not stop accelerating

### ISSUE THREAD

**Issue by mchloupek** [Dimencia/DU-Orbital-Hud#188]
On occasion, autopilot does not stop accelerating a wastes fuel. HUD reports speed 29 998 km/h, game reports 29 999 hm/h.
The screenshot below is taken midway between Sanctuary and Madis. This never happened before the 0.23 DU update.
![image](https://user-images.githubusercontent.com/2405796/102013028-c877c280-3d4d-11eb-9684-ddd0dcfe2e56.png)

**Comment by Archaegeo** [comment]
Recommend setting MaxGameVelocity to 8319 m/s (29950 km/hr) so you always exceed it and shut off, this one is too hard to track otherwise.

**Comment by mchloupek** [comment]
It works fine in recent game releases. 

In this case: "Recommend setting MaxGameVelocity to 8319 m/s (29950 km/hr)" I would suggest changing default HUD settings.

**Comment by Dimencia** [comment]
AP keeps burning even after you've reached max speed if you haven't achieved a safe entry trajectory (within 1km of target Projected Altitude).  This can happen randomly depending on how powerful your ship's space engines are, what speed you were at and what planet you were near when you engaged AP - ie if your engines can get you to max speed before the autopilot has a chance to adjust the trajectory, this can happen.  It is intentional - if they are still firing, the orbit may not be stable or safe, and after an annoyingly long time, it can finish aligning even from max speed
