### ISSUE TITLE
cruise

### ISSUE THREAD

**Issue by SvarogZ** [Dimencia/DU-Orbital-Hud#233]
Cannot switch from cruise to throttle mode by Ctrl+R.
Looks like this issue appears in the last version.

**Comment by Dimencia** [comment]
Lua can't actually do anything about you hitting Ctrl+R, it's just not something we can mess with.  Ctrl+R (and cruise mode in general) doesn't work on Remote Controllers and hasn't for a while, if that's what you mean.  Otherwise a restart and cache flush should probably fix it

**Comment by SvarogZ** [comment]
The old version of the script worked fine (before 5.11).
It's not my local issue, because the same behaviour was observed by all pilots for this ship.
Anyway, probably it was fixed in the new version.

**Comment by Dimencia** [comment]
I mean we can't even hijack that hotkey, we tried, it's not lua related.  But also it's alt+r, maybe the problem

**Comment by SvarogZ** [comment]
The problem is the script has changed this mode back to the cruise.

**Comment by Dimencia** [comment]
You may be confusing our new throttled-cruise implementation with cruise?  We only swap from cruise to throttle if it's during reentry, and it's not forced on.  
If you mean in altitude hold or going to a waypoint, you can disable AtmoSpeedAssist if you want to go back to cruise - but the new implementation of throttle limits you to your defined AtmoSpeedLimit, while still letting you easily throttle up/down.  We use it instead of cruise in all AP situations except the early parts of reentry, now, and it serves all the same purposes.  You can use alt+mousewheel to change the cruise speed, up to your AtmoSpeedLimit, which you can define with `/G AtmoSpeedLimit 1100` in the lua tab, for example.
