### ISSUE TITLE
[Feature Request] - Altimeter Above Ground Level

### ISSUE THREAD

**Issue by Mishka6783** [Dimencia/DU-Orbital-Hud#32]
Is there any way to make the altimeter show Above Ground level even if another sensor was needed?

**Comment by Dimencia** [comment]
There is not; everything that can measure distance has a (pretty short) max range.  That's why autolanding is so... boring.  The best it can do is pitch down and slowly cruise until vertical boosters start to fire, and then it knows it's near the ground.

I'd love to it add it but we just can't get the data :(
