### ISSUE TITLE
FPS drop during Autopilot

### ISSUE THREAD

**Issue by TBrawand** [Dimencia/DU-Orbital-Hud#61]
System: Ryzen 9 3900X, Nvidia 2080 Super, 32GB RAM
Situation: Using the autopilot to fly to another planet

During the acceleration period the FPS drop to 8-10, one CPU Core goes up to around 95% while the overall stays around 10%, the GPU is the same time around 25-30%... As soon as the acceleration is finished (ship reaches 29 999km/h and the HUD remarks to Autopilot Cruising) the FPS go up to 70+ stable.
The moment it starts to slow down (Autopilot Braking), the fps go back down to 8 and the very same core again up to around 95%...
I assume that this is based on a LUA-Implementation problem (using only one core or whatever) but wanted to ask if this is the same for others or if it's only me and maybe you can do something against it ;)

**Comment by Dimencia** [comment]
That is a very strange report that we haven't had before.  FPS drops will generally occur a. On planet when using the HUD, and b. If you hit tab and click on anything due to a DU bug (and this usually isn't resolved until you get out of the seat)
I'd suggest restarting DU and seeing if it's better next trip, sometimes DU's just like that

**Comment by TBrawand** [comment]
I have the same even after a DU restart... As said I assume it's not cause of your script but cause of DU itself ;)
But thanks for the answer 👍
