### ISSUE TITLE
The problem with cruising on a large ship

### ISSUE THREAD

**Issue by NeirRon** [Dimencia/DU-Orbital-Hud#89]
In space, when you turn on the cruise mode, you can see that the engines are working at full power, but the ship drops speed to 22-23 km / h and remains in place. There is no brake indication. In the safe reentry mode, the cruise is also activated at 1050 km / h, the engines are running at full power and the ship is stopped at a low speed

**Comment by Archaegeo** [comment]
The issue is with cruise control, not the HUD.  In DU, cruise control when activated tries to make the current max vector hit the target speed, braking in all other directions.  So if you engage cruise control while down > forward, then its going to brake in every direction but down, and fire engines at full trying to make you go faster that way.  Unfortunately all your engines are facing forward.  So you end up braking in all directions but down, with only gravity trying to speed you up that way.  

Same thing if you were going up faster than forward when you set cruise control.  Since Re-Entry just angles you down 20 (relative to planet) and sets cruise control to 1050 km/hr, if you arent moving forward already, you might run into issues.
