### ISSUE TITLE
Autopilot Spinning out.

### ISSUE THREAD

**Issue by EvilBoy199** [Dimencia/DU-Orbital-Hud#9]
Hey the original Full_Hud would Align properly but the latest two archeago and button makes my ship spin and waste fuel when i try to align. Now im sure its the way i built my ship and me needing to tweak some settings in the lua but i have no clue what to tinker with.

**Comment by Dimencia** [comment]
It was adjusted so that now it aligns your velocity vector with the target, instead of just pointing at it, for much better accuracy.  Early on in the maneuver this will mean turning sideways and a bit of bouncing back and forth to line it up perfectly, but it should even out once you get going. 
If it keeps giving you trouble you can try to crank up the Damping in the Lua Parameters, but that sounds like what it's supposed to be doing.  

If you start very near a planet, it will 1. not do this while in orbit, and then 2. have to do this *really aggressively* as soon as it leaves orbit, because your trajectory is way off.  This means in some cases it will bounce into and out of orbit and go back and forth, but it's still doing what it's supposed to be (most likely)

Anyway I should also mention that we're not really updating anything except buttonHUD now, so that's probably your safest option, but I still try to fix any bugs I find in the older versions in case people still want to use them.
